### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by SaFrMo** [vaneenige/phenomenon#11]
Hey! Fantastic library, first of all, this is so useful - thank you for it!

I'm getting an `unexpected token export` error when I use the library in Nuxt and wanted to see if there was any quick fix I was missing. To reproduce:

1. Clone and install [this repo](https://github.com/SaFrMo/phenomenon-export-bug)
1. `npm run dev`

Expected: See a blank page with an h2 reading "export bug demo"
Actual: See Nuxt's "Unexpected token export" error page

If this is something Nuxt-specific, I can do more digging, but I wanted to mention it and see if you've come across it before. In any case, thanks again for the excellent work!

**Comment by SaFrMo** [comment]
Also, to clarify, the only relevant Vue template file is [here](https://github.com/SaFrMo/phenomenon-export-bug/blob/master/layouts/default.vue) - everything else is Nuxt defaults.

**Comment by SaFrMo** [comment]
Found a fix! Instead of these lines:

```html
import Phenomenon from 'phenomenon-px'

export default {
    mounted() {
        let fragment = ''

        const uniforms = {}

        const render = () => {}

        // kick loop
        Phenomenon(fragment, uniforms, render, this.$refs.canvas)
    }
}
```

I moved Phenomenon from an `import` to a `require` statement:

```html

export default {
    mounted() {
        let fragment = ''

        const uniforms = {}

        const render = () => {}

        // here!
        const Phenomenon = require('phenomenon-px').default

        // kick loop
        Phenomenon(fragment, uniforms, render, this.$refs.canvas)
    }
}
```

Works as expected now! Closing unless you have any other thoughts, @vaneenige 😄

**Comment by vaneenige** [comment]
Hey Sander, that's an odd issue I have not seen before, glad you found a fix! 🙌
