### ISSUE TITLE
Change near/far clip plane

### ISSUE THREAD

**Issue by Jijjy** [vaneenige/phenomenon#12]
Firstly, big fan - thanks for making this. I noticed the "far" clip plane seems to be 100 which was too small for me, i've modified the projection matrix in my project to be 0.1 to 1000

Could this be made customizable or changed?

**Comment by SaFrMo** [comment]
I ran into this same issue and set up a PR to add this option in #13 - thanks @vaneenige and @Jijjy !

**Comment by vaneenige** [comment]
Merged in https://github.com/vaneenige/phenomenon/pull/13 and published to npm!
