### ISSUE TITLE
LOGO PROPOSAL for PHENOMENON

### ISSUE THREAD

**Issue by joshuacarlito** [vaneenige/phenomenon#2]
Hi @vaneenige , I have observed that Phenomenon has no logo yet. Lately, I have been making graphics design on open source projects and to a blockchain. I love making graphics design and if you want a logo of phenomenon, I am very free to make a logo for the said project. Just reply idea or suggestion for the logo and I will also make my own logo style. Thank you :)

**Comment by vaneenige** [comment]
Hey @joshuacarlito, thank you for reaching out! Phenomenon will have a logo soon as it's currently being worked on, therefore I'll be closing this issue.
