### ISSUE TITLE
Comments to explain this section code

### ISSUE THREAD

**Issue by mikaelhadler** [vaneenige/phenomenon#4]
Hello! You can explain this section code? No have any comments, so for me, it's  so difficult to understand, if you can, please? <3

https://github.com/vaneenige/phenomenon/blob/98923a77cae65999fd06d211a3b254d2d195eb60/src/index.js#L98

**Comment by vaneenige** [comment]
Hey Mikael, I've added some comments to explain what happens in that part of the library. The changes can be found in this commit (c026d496b74ffc3b4a8d10a218fccf954fa23745)!
