### ISSUE TITLE
Chaining for post-process ?

### ISSUE THREAD

**Issue by kohaistyle** [vaneenige/phenomenon#6]
Very nice effort for a KISS and low-level webgl fw ! Seems to have passed the 2kb limit though ( 4.5k from the npm install ) :laughing: 

Anyway, do you have plans or ideas on how to chain shaders to create some kind of renderer pipeline ? Saw you can add several nodes to the renderer, but no way to chain/access them ?

ANyway, keep up the good work !

**Comment by vaneenige** [comment]
Hey @kohaistyle! 

The `2kB` I'm referring to the gzip size which can be obtained by `npm run build`. The size you've mentioned is the uncompressed size!

Chaining shaders is actually something I've had on my mind this morning. There are two ways I came up with that might work:

- The ability to update attributes once an animation is done. This way the same animation can run again, but with different values. I'll have to check if this method is feasible in terms of speed.

- The ability to store all attributes for the timeline up front and do some switches inside the shader. This might get very complicated, but is possible in the current version of the library.

Instances added to the renderer are available through `renderer.instances`.

Is this similar to what you had in mind? 🙌
